version: "3.7"

services:

  db:
    image: "postgres:14.0"
    volumes:
      - ${PWD}/data/db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
      image: redis:6-alpine
      restart: unless-stopped
      command: >
          --requirepass ${REDIS_PASSWORD}
      volumes:
      - ${PWD}/data/redis-data:/data
      ports:
        - 6379:6379
      mem_limit: 4000M
      memswap_limit: 5000M
      mem_reservation: 1000M